### ISSUE TITLE
missing prereqs on ubuntu

### ISSUE THREAD

**Issue by catherinedevlin** [18F/regulations-site#1]
On Ubuntu 14.04, `buildout` died for me with `xslt-config: not found`.  Following the answer at http://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu, I used

    apt-get install libxml2-dev libxslt1-dev

which fixed the problem.  Should this be added to the (excellent) installation instructions?

**Comment by cmc333333** [comment]
#42 resolved this by removing the need for libxml
