### ISSUE TITLE
Error notifications can't be dismissed

### ISSUE THREAD

**Issue by jmcarp** [18F/regulations-site#113]
<img width="673" alt="screen shot 2016-03-02 at 4 46 36 pm" src="https://cloud.githubusercontent.com/assets/1633460/13476571/71cc0144-e096-11e5-8a19-c750b6c01daa.png">

As far as I can tell, error notices from `MainView#displayError` can't be dismissed, so that if a user encounters a few of them on the same view, they'll stack up and start to full the center pane. I would expect these alerts to be dismissable, or to expire eventually.

**Comment by xtine** [comment]
How do you get the network error notification to appear?

**Comment by jmcarp** [comment]
If you're running the app locally:

* Go to a regulation
* Open the search panel
* Kill your local server
* Search for anything

I *was* running into this on empty searches before we fixed https://github.com/18F/atf-eregs/issues/374, but now the error should be less common. Maybe it's rare enough that it's not worth fixing--I'll defer to folks who've spent more time on the project than me--meaning everybody :sunglasses:

**Comment by xtine** [comment]
I looked into the issue in the JS and it was a really quick fix since network error is basically the only type of error notification that's displayed to the user. Take a look at the PR and let me know if you have any other suggestions.

**Comment by cmc333333** [comment]
I think this was resolved in #116
