### ISSUE TITLE
Compile Frontend should pass up error codes up

### ISSUE THREAD

**Issue by cmc333333** [18F/regulations-site#164]
If the JS commands error out, `compile_frontend` won't pass up the error message.

This leads to "passing" tests: 
<img width="896" alt="screen shot 2016-03-28 at 1 37 33 pm" src="https://cloud.githubusercontent.com/assets/326918/14084738/456d0c52-f4ea-11e5-943b-f13910ff84ec.png">

**Comment by jmcarp** [comment]
Will fix unless you're already doing this @cmc333333. By the way, was this a regression? I didn't see explicit status checks in `compile_frontend`.

**Comment by jmcarp** [comment]
Also "fix" looks to mean s/subprocess.call/subprocess.check_call/

**Comment by cmc333333** [comment]
I'm not; I don't believe it ever checked. I just noticed a build which _should_ have failed didn't. Go for it!
